export const CURRENT_SEARCHED_POKEMON ='CURRENT_SEARCHED_POKEMON';
export const CURRENT_POKEMON_DATA ='CURRENT_POKEMON_DATA';
export const ADD_POKEMON_TO_LIST = 'ADD_POKEMON_TO_LIST';
export const SET_POKEMON_LIST_FROM_LOCAL = 'SET_POKEMON_LIST_FROM_LOCAL';
export const DEL_POKEMON_FROM_LIST = 'DEL_POKEMON_FROM_LIST';
export const FAVORITES_LIST = 'FAVORITES_LIST';
export const SET_FAVORITES_LIST_FROM_LOCAL = 'SET_FAVORITES_LIST_FROM_LOCAL';
export const SET_CURRENT_TRAINER = 'SET_CURRENT_TRAINER';

